INSERT INTO USER (ID, USERNAME, PASSWORD, ENABLED) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 1);
INSERT INTO USER (ID, USERNAME, PASSWORD, ENABLED) VALUES (2, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 1);
INSERT INTO USER (ID, USERNAME, PASSWORD, ENABLED) VALUES (3, 'disabled', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 0);

INSERT INTO ROLE (ID, ROLE) VALUES (1, 'USER');
INSERT INTO ROLE (ID, ROLE) VALUES (2, 'ADMIN');

INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (3, 1);
